import SwiftProtobuf
import XCTest

@testable import SwiftProtoParser

/// Integration tests for client-provided `.proto` files.
///
/// - **Tier 1a** (9 files): standard options only → exact bytes comparison against `protoc`.
/// - **Tier 1b** (2 files): custom extension options (`buf.validate`, `google.api.http`)
///   → targeted comparison of `uninterpreted_option` arrays against `proto-unlinked-gen`
///   (because standard options like `go_package` are stored as typed fields by SwiftProtoParser
///   but as uninterpreted_option by the Go-tool).
///
/// Reference `.pb` files live in `Tests/TestResources/ClientProtoDescriptors/` and are
/// generated by `Scripts/generate_extension_option_descriptors.sh`.
final class ClientProtoIntegrationTests: XCTestCase {

  // MARK: - Tier 1a: standard options only → exact bytes comparison with protoc

  func test_bookProcessedMessage_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pubsub/book_processed.message.proto",
      pbFile: "book_processed_message.pb"
    )
  }

  func test_loanHistoryMessage_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pubsub/loan_history.message.proto",
      pbFile: "loan_history_message.pb"
    )
  }

  func test_catalogChangesMessage_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pubsub/catalog_changes.message.proto",
      pbFile: "catalog_changes_message.pb"
    )
  }

  func test_healthMessage_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pb_system/health.message.proto",
      pbFile: "health_message.pb"
    )
  }

  func test_healthService_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pb_system/health.service.proto",
      pbFile: "health_service.pb"
    )
  }

  func test_publicTypes_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pb_catalog/public_types.proto",
      pbFile: "public_types.pb"
    )
  }

  func test_bookMessage_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pb_circulation/book.message.proto",
      pbFile: "book_message.pb"
    )
  }

  func test_bookService_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pb_circulation/book.service.proto",
      pbFile: "book_service.pb"
    )
  }

  func test_summaryCount_matchesProtoc() throws {
    try assertMatchesProtoc(
      protoFile: "pb_analytics/summary_count.proto",
      pbFile: "summary_count.pb"
    )
  }

  // MARK: - Tier 1b: custom extension options → targeted uninterpreted_option comparison

  /// Verifies that gateway.message.proto's custom `(buf.validate.field)` options are
  /// correctly parsed into `uninterpreted_option` with proper NameParts.
  ///
  /// We compare ONLY the `uninterpreted_option` arrays (not typed standard option fields
  /// such as `go_package`) because the Go-tool stores ALL options as uninterpreted while
  /// SwiftProtoParser handles standard options as typed fields.
  func test_gatewayMessage_customOptionsMatchGoTool() throws {
    try assertCustomOptionsMatchGoTool(
      protoFile: "pb_gateway/gateway.message.proto",
      pbFile: "gateway_message.pb"
    )
  }

  func test_gatewayService_customOptionsMatchGoTool() throws {
    try assertCustomOptionsMatchGoTool(
      protoFile: "pb_gateway/gateway.service.proto",
      pbFile: "gateway_service.pb"
    )
  }

  // MARK: - Tier 1a implementation

  private func assertMatchesProtoc(
    protoFile: String,
    pbFile: String,
    file: StaticString = #file,
    line: UInt = #line
  ) throws {
    let protoPath = testResourcePath(for: "ClientProtos/\(protoFile)")
    let pbPath = testResourcePath(for: "ClientProtoDescriptors/\(pbFile)")

    guard FileManager.default.fileExists(atPath: pbPath) else {
      XCTFail(
        "Reference descriptor not found at \(pbPath). Run Scripts/generate_extension_option_descriptors.sh",
        file: file,
        line: line
      )
      return
    }

    let referenceProto = try loadTargetProto(from: pbPath, named: protoFile)
    let actualProto = try parseWithSwiftProtoParser(
      protoPath: protoPath,
      protoFile: protoFile,
      importPaths: clientProtoImportPaths(for: protoPath)
    )

    let normRef = normalise(referenceProto)
    let normActual = normalise(actualProto)

    assertBytesEqual(normActual, normRef, label: protoFile, file: file, line: line)
  }

  // MARK: - Tier 1b implementation

  /// Parses the proto file and the Go-tool reference, then asserts that all
  /// `uninterpreted_option` arrays in each descriptor element match exactly.
  private func assertCustomOptionsMatchGoTool(
    protoFile: String,
    pbFile: String,
    file: StaticString = #file,
    line: UInt = #line
  ) throws {
    let protoPath = testResourcePath(for: "ClientProtos/\(protoFile)")
    let pbPath = testResourcePath(for: "ClientProtoDescriptors/\(pbFile)")

    guard FileManager.default.fileExists(atPath: pbPath) else {
      XCTFail(
        "Reference descriptor not found at \(pbPath). Run Scripts/generate_extension_option_descriptors.sh",
        file: file,
        line: line
      )
      return
    }

    let referenceProto = try loadTargetProto(from: pbPath, named: protoFile)
    let actualProto = try parseWithSwiftProtoParser(
      protoPath: protoPath,
      protoFile: protoFile,
      importPaths: clientProtoImportPaths(for: protoPath)
    )

    assertUninterpretedOptionsMatch(actualProto, referenceProto, label: protoFile, file: file, line: line)
  }

  /// Returns only the extension-type uninterpreted options (where the first name part has `isExtension == true`).
  ///
  /// This filters out standard typed options like `go_package` that the Go-tool stores as
  /// uninterpreted_option but SwiftProtoParser correctly handles as typed fields.
  private func extensionOptions(
    from opts: [Google_Protobuf_UninterpretedOption]
  ) -> [Google_Protobuf_UninterpretedOption] {
    opts.filter { $0.name.first?.isExtension == true }
  }

  /// Asserts that all custom extension `uninterpreted_option` entries in `actual` match `expected`
  /// across file-level options, messages, fields, services, and methods.
  ///
  /// Standard options (like `go_package`) are intentionally excluded from comparison because
  /// the Go-tool stores them as `uninterpreted_option` while SwiftProtoParser stores them as
  /// typed fields.
  private func assertUninterpretedOptionsMatch(
    _ actual: Google_Protobuf_FileDescriptorProto,
    _ expected: Google_Protobuf_FileDescriptorProto,
    label: String,
    file: StaticString,
    line: UInt
  ) {
    // File-level custom options (extension options only)
    let actualFileOpts = extensionOptions(from: actual.options.uninterpretedOption)
      .map { normaliseAggregateValue($0) }
    let expectedFileOpts = extensionOptions(from: expected.options.uninterpretedOption)
      .map { normaliseAggregateValue($0) }
    XCTAssertEqual(
      actualFileOpts,
      expectedFileOpts,
      "\(label): file-level uninterpreted_options mismatch",
      file: file,
      line: line
    )

    // Per-message and per-field options
    for (msgIdx, (actualMsg, expectedMsg)) in zip(actual.messageType, expected.messageType).enumerated() {
      assertMessageUninterpretedOptionsMatch(
        actualMsg,
        expectedMsg,
        path: "\(label).message[\(msgIdx)].\(actualMsg.name)",
        file: file,
        line: line
      )
    }

    // Service and method options
    for (svcIdx, (actualSvc, expectedSvc)) in zip(actual.service, expected.service).enumerated() {
      let svcPath = "\(label).service[\(svcIdx)].\(actualSvc.name)"
      let actualSvcOpts = extensionOptions(from: actualSvc.options.uninterpretedOption)
        .map { normaliseAggregateValue($0) }
      let expectedSvcOpts = extensionOptions(from: expectedSvc.options.uninterpretedOption)
        .map { normaliseAggregateValue($0) }
      XCTAssertEqual(actualSvcOpts, expectedSvcOpts, "\(svcPath): service options mismatch", file: file, line: line)

      for (mIdx, (am, em)) in zip(actualSvc.method, expectedSvc.method).enumerated() {
        let mPath = "\(svcPath).method[\(mIdx)].\(am.name)"
        let actualMOpts = extensionOptions(from: am.options.uninterpretedOption)
          .map { normaliseAggregateValue($0) }
        let expectedMOpts = extensionOptions(from: em.options.uninterpretedOption)
          .map { normaliseAggregateValue($0) }
        XCTAssertEqual(actualMOpts, expectedMOpts, "\(mPath): method options mismatch", file: file, line: line)
      }
    }
  }

  private func assertMessageUninterpretedOptionsMatch(
    _ actual: Google_Protobuf_DescriptorProto,
    _ expected: Google_Protobuf_DescriptorProto,
    path: String,
    file: StaticString,
    line: UInt
  ) {
    // Message options (extension options only)
    let aOpts = extensionOptions(from: actual.options.uninterpretedOption)
      .map { normaliseAggregateValue($0) }
    let eOpts = extensionOptions(from: expected.options.uninterpretedOption)
      .map { normaliseAggregateValue($0) }
    XCTAssertEqual(aOpts, eOpts, "\(path): message options mismatch", file: file, line: line)

    // Field options (extension options only)
    for (fIdx, (af, ef)) in zip(actual.field, expected.field).enumerated() {
      let fPath = "\(path).field[\(fIdx)].\(af.name)"
      let afOpts = extensionOptions(from: af.options.uninterpretedOption)
        .map { normaliseAggregateValue($0) }
      let efOpts = extensionOptions(from: ef.options.uninterpretedOption)
        .map { normaliseAggregateValue($0) }
      XCTAssertEqual(afOpts, efOpts, "\(fPath): field options mismatch", file: file, line: line)
    }

    // Nested messages
    for (nIdx, (an, en)) in zip(actual.nestedType, expected.nestedType).enumerated() {
      assertMessageUninterpretedOptionsMatch(
        an,
        en,
        path: "\(path).nested[\(nIdx)].\(an.name)",
        file: file,
        line: line
      )
    }
  }

  // MARK: - Normalisation

  private func normalise(_ proto: Google_Protobuf_FileDescriptorProto) -> Google_Protobuf_FileDescriptorProto {
    var p = proto
    p.clearSourceCodeInfo()
    p.clearEdition()
    p.messageType = p.messageType.map { normaliseMessage($0) }
    return p
  }

  private func normaliseMessage(_ proto: Google_Protobuf_DescriptorProto) -> Google_Protobuf_DescriptorProto {
    var p = proto
    p.nestedType = p.nestedType.map { normaliseMessage($0) }
    return p
  }

  private func normaliseAggregateValue(
    _ u: Google_Protobuf_UninterpretedOption
  ) -> Google_Protobuf_UninterpretedOption {
    guard u.hasAggregateValue else { return u }
    var copy = u
    let normalized = copy.aggregateValue
      .components(separatedBy: .whitespaces)
      .filter { !$0.isEmpty }
      .joined(separator: " ")
    copy.aggregateValue = normalized
    return copy
  }

  // MARK: - Parse helpers

  private func parseWithSwiftProtoParser(
    protoPath: String,
    protoFile: String,
    importPaths: [String]
  ) throws -> Google_Protobuf_FileDescriptorProto {
    let result = SwiftProtoParser.parseFile(protoPath, importPaths: importPaths)
    guard case .success(let fileSet) = result else {
      if case .failure(let error) = result {
        throw ClientIntegrationError.parseFailed(protoFile, error.localizedDescription)
      }
      throw ClientIntegrationError.parseFailed(protoFile, "unknown error")
    }
    let lastName = URL(fileURLWithPath: protoFile).lastPathComponent
    guard
      let proto = fileSet.file.first(where: {
        $0.name.hasSuffix(lastName) || $0.name == protoFile
      })
    else {
      throw ClientIntegrationError.protoNotFound(protoFile)
    }
    return proto
  }

  private func loadTargetProto(from pbPath: String, named protoFile: String) throws
    -> Google_Protobuf_FileDescriptorProto
  {
    let data = try Data(contentsOf: URL(fileURLWithPath: pbPath))
    let fds = try Google_Protobuf_FileDescriptorSet(serializedBytes: Array(data))
    let lastName = URL(fileURLWithPath: protoFile).lastPathComponent
    if let proto = fds.file.first(where: { $0.name.hasSuffix(lastName) || $0.name == protoFile }) {
      return proto
    }
    guard let first = fds.file.first else {
      throw ClientIntegrationError.protoNotFound(protoFile)
    }
    return first
  }

  private func clientProtoImportPaths(for protoPath: String) -> [String] {
    let clientRoot = testResourcePath(for: "ClientProtos")
    return [clientRoot, "/usr/local/include"]
  }

  // MARK: - Comparison

  private func assertBytesEqual(
    _ actual: Google_Protobuf_FileDescriptorProto,
    _ expected: Google_Protobuf_FileDescriptorProto,
    label: String,
    file: StaticString,
    line: UInt
  ) {
    do {
      let actualBytes: [UInt8] = try actual.serializedBytes()
      let expectedBytes: [UInt8] = try expected.serializedBytes()
      if actualBytes == expectedBytes { return }

      let actualJSON = (try? actual.jsonString()) ?? "<json failed>"
      let expectedJSON = (try? expected.jsonString()) ?? "<json failed>"
      XCTFail(
        "Descriptor bytes mismatch for \(label).\n"
          + "--- expected (protoc) ---\n\(expectedJSON)\n"
          + "--- actual (SwiftProtoParser) ---\n\(actualJSON)",
        file: file,
        line: line
      )
    }
    catch {
      XCTFail("Serialization error for \(label): \(error)", file: file, line: line)
    }
  }

  // MARK: - Path helpers

  private func testResourcePath(for relativePath: String) -> String {
    let thisFile = URL(fileURLWithPath: #file)
    let projectRoot =
      thisFile
      .deletingLastPathComponent()  // ProductTests
      .deletingLastPathComponent()  // SwiftProtoParserTests
      .deletingLastPathComponent()  // Tests
      .deletingLastPathComponent()  // project root
    return projectRoot.appendingPathComponent("Tests/TestResources/\(relativePath)").path
  }

  enum ClientIntegrationError: Error {
    case parseFailed(String, String)
    case protoNotFound(String)
  }
}
