import SwiftProtobuf
import XCTest

@testable import SwiftProtoParser

/// Integration tests comparing SwiftProtoParser's descriptor output against protoc and proto-unlinked-gen.
///
/// - **Tier 1a**: binary descriptors generated by `protoc` (standard options only protos).
/// - **Tier 1b**: binary descriptors generated by `proto-unlinked-gen` (protocompile unlinked)
///               for protos with custom extension options. Custom options are stored as
///               `uninterpreted_option` in both tools, making exact comparison possible.
///
/// Reference `.pb` files live in `Tests/TestResources/HandcraftedDescriptors/` and are
/// generated by `Scripts/generate_extension_option_descriptors.sh`.
final class ExtensionOptionIntegrationTests: XCTestCase {

  // MARK: - Tier 1a: Standard options only → exact bytes comparison with protoc

  func test_standardOptions_matchesProtocDescriptor() throws {
    try assertMatchesProtoc(
      protoName: "test_standard_options",
      protoFile: "test_standard_options.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_extensionRangeWithOptions_matchesProtocDescriptor() throws {
    try assertMatchesProtoc(
      protoName: "test_ext_range_with_options",
      protoFile: "test_ext_range_with_options.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  // MARK: - Tier 1b: Custom extension options → exact bytes comparison with Go-tool

  func test_customOptionsBasic_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_custom_options_basic",
      protoFile: "test_custom_options_basic.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_subfieldPath_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_subfield_path",
      protoFile: "test_subfield_path.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_messageLiteralOption_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_message_literal_option",
      protoFile: "test_message_literal_option.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_allOptionContexts_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_all_option_contexts",
      protoFile: "test_all_option_contexts.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_numberOptionValues_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_number_option_values",
      protoFile: "test_number_option_values.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_qualifiedExtSubfield_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_qualified_ext_subfield",
      protoFile: "test_qualified_ext_subfield.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_multiOptionsField_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_multi_options_field",
      protoFile: "test_multi_options_field.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  func test_repeatedInExtend_matchesGoToolDescriptor() throws {
    try assertMatchesGoTool(
      protoName: "test_repeated_in_extend",
      protoFile: "test_repeated_in_extend.proto",
      inDirectory: "HandcraftedProtos"
    )
  }

  // MARK: - Tier 1a helper

  private func assertMatchesProtoc(
    protoName: String,
    protoFile: String,
    inDirectory directory: String,
    file: StaticString = #file,
    line: UInt = #line
  ) throws {
    let protoPath = testResourcePath(for: "\(directory)/\(protoFile)")
    let pbPath = testResourcePath(for: "HandcraftedDescriptors/\(protoName).pb")

    guard FileManager.default.fileExists(atPath: pbPath) else {
      XCTFail(
        "Reference descriptor not found at \(pbPath). Run Scripts/generate_extension_option_descriptors.sh",
        file: file,
        line: line
      )
      return
    }

    let referenceProto = try loadTargetProto(from: pbPath, named: protoFile)
    let actualProto = try parseWithSwiftProtoParser(protoPath: protoPath, protoFile: protoFile)

    let normRef = normalise(referenceProto)
    let normActual = normalise(actualProto)

    assertBytesEqual(normActual, normRef, label: protoName, file: file, line: line)
  }

  // MARK: - Tier 1b helper

  private func assertMatchesGoTool(
    protoName: String,
    protoFile: String,
    inDirectory directory: String,
    file: StaticString = #file,
    line: UInt = #line
  ) throws {
    let protoPath = testResourcePath(for: "\(directory)/\(protoFile)")
    let pbPath = testResourcePath(for: "HandcraftedDescriptors/\(protoName).pb")

    guard FileManager.default.fileExists(atPath: pbPath) else {
      XCTFail(
        "Reference descriptor not found at \(pbPath). Run Scripts/generate_extension_option_descriptors.sh",
        file: file,
        line: line
      )
      return
    }

    let referenceProto = try loadTargetProto(from: pbPath, named: protoFile)
    let actualProto = try parseWithSwiftProtoParser(protoPath: protoPath, protoFile: protoFile)

    let normRef = normaliseForGoTool(referenceProto)
    let normActual = normaliseForGoTool(actualProto)

    assertBytesEqual(normActual, normRef, label: protoName, file: file, line: line)
  }

  // MARK: - Parse with SwiftProtoParser

  private func parseWithSwiftProtoParser(protoPath: String, protoFile: String) throws
    -> Google_Protobuf_FileDescriptorProto
  {
    let protoDir = URL(fileURLWithPath: protoPath).deletingLastPathComponent().path
    let result = SwiftProtoParser.parseFile(protoPath, importPaths: [protoDir, "/usr/local/include"])
    guard case .success(let fileSet) = result else {
      if case .failure(let error) = result {
        throw IntegrationTestError.parseFailed(protoFile, error.localizedDescription)
      }
      throw IntegrationTestError.parseFailed(protoFile, "unknown error")
    }
    guard let proto = fileSet.file.first(where: { $0.name.hasSuffix(protoFile) || $0.name == protoFile }) else {
      throw IntegrationTestError.protoNotFound(protoFile)
    }
    return proto
  }

  // MARK: - Load reference .pb

  private func loadTargetProto(from pbPath: String, named protoFile: String) throws
    -> Google_Protobuf_FileDescriptorProto
  {
    let data = try Data(contentsOf: URL(fileURLWithPath: pbPath))
    let fds = try Google_Protobuf_FileDescriptorSet(serializedBytes: Array(data))
    guard let proto = fds.file.first(where: { $0.name.hasSuffix(protoFile) || $0.name == protoFile }) else {
      // If only one file, use it directly
      guard let first = fds.file.first else {
        throw IntegrationTestError.protoNotFound(protoFile)
      }
      return first
    }
    return proto
  }

  // MARK: - Normalisation

  /// Normalise for protoc comparison: strip source_code_info and edition.
  private func normalise(_ proto: Google_Protobuf_FileDescriptorProto) -> Google_Protobuf_FileDescriptorProto {
    var p = proto
    p.clearSourceCodeInfo()
    p.clearEdition()
    p.messageType = p.messageType.map { normaliseMessage($0) }
    return p
  }

  /// Normalise for Go-tool (protocompile unlinked) comparison.
  ///
  /// The Go-tool and SwiftProtoParser differ in systematic, expected ways:
  ///
  /// 1. **File name**: Go-tool stores the absolute path that was passed on the CLI;
  ///    SwiftProtoParser uses just the filename. → normalise to filename only.
  ///
  /// 2. **Type names** (`typeName`, `inputType`, `outputType`): SwiftProtoParser resolves
  ///    types within the same file and stores fully-qualified names with a leading `.`
  ///    (e.g. `.pkg.Foo`); the Go-tool stores the raw name from the source (e.g. `Foo`).
  ///    → strip leading `.` and any `package.` prefix.
  ///
  /// 3. **Extendee**: After the extendee-bug fix, SwiftProtoParser stores `.google.protobuf.X`
  ///    (absolute, with leading dot); the Go-tool stores `google.protobuf.X` (no leading dot).
  ///    → strip leading `.`.
  ///
  /// 4. **aggregate_value whitespace**: already handled by `normaliseAggregateValue`.
  private func normaliseForGoTool(_ proto: Google_Protobuf_FileDescriptorProto) -> Google_Protobuf_FileDescriptorProto {
    var p = normalise(proto)
    let pkg = p.package

    // 1. File name: keep only the last path component.
    p.name = URL(fileURLWithPath: p.name).lastPathComponent

    // 2–3. Type references and aggregate values across all descriptor elements.
    p.messageType = p.messageType.map { normaliseMessageForGoTool($0, package: pkg) }
    p.extension = p.extension.map { normaliseFieldForGoTool($0, package: pkg) }
    p.service = p.service.map { normaliseSvcForGoTool($0, package: pkg) }
    if p.hasOptions {
      p.options.uninterpretedOption = p.options.uninterpretedOption.map { normaliseAggregateValue($0) }
    }
    return p
  }

  // MARK: - Go-tool normalisation helpers

  private func normaliseTypeName(_ name: String, package: String) -> String {
    // Strip leading dot to match the Go-tool's format.
    var n = name.hasPrefix(".") ? String(name.dropFirst()) : name
    // Strip package prefix when present (e.g. "pkg.Foo" → "Foo").
    if !package.isEmpty, n.hasPrefix(package + ".") {
      n = String(n.dropFirst(package.count + 1))
    }
    return n
  }

  private func normaliseMessageForGoTool(
    _ proto: Google_Protobuf_DescriptorProto,
    package: String
  ) -> Google_Protobuf_DescriptorProto {
    var p = proto
    if p.hasOptions {
      p.options.uninterpretedOption = p.options.uninterpretedOption.map { normaliseAggregateValue($0) }
    }
    p.field = p.field.map { normaliseFieldForGoTool($0, package: package) }
    p.oneofDecl = p.oneofDecl.map { od -> Google_Protobuf_OneofDescriptorProto in
      var od2 = od
      if od2.hasOptions {
        od2.options.uninterpretedOption = od2.options.uninterpretedOption.map { normaliseAggregateValue($0) }
      }
      return od2
    }
    p.enumType = p.enumType.map { ed -> Google_Protobuf_EnumDescriptorProto in
      var ed2 = ed
      if ed2.hasOptions {
        ed2.options.uninterpretedOption = ed2.options.uninterpretedOption.map { normaliseAggregateValue($0) }
      }
      ed2.value = ed2.value.map { ev -> Google_Protobuf_EnumValueDescriptorProto in
        var ev2 = ev
        if ev2.hasOptions {
          ev2.options.uninterpretedOption = ev2.options.uninterpretedOption.map { normaliseAggregateValue($0) }
        }
        return ev2
      }
      return ed2
    }
    p.nestedType = p.nestedType.map { normaliseMessageForGoTool($0, package: package) }
    return p
  }

  private func normaliseFieldForGoTool(
    _ field: Google_Protobuf_FieldDescriptorProto,
    package: String
  ) -> Google_Protobuf_FieldDescriptorProto {
    var f = field
    if !f.typeName.isEmpty {
      f.typeName = normaliseTypeName(f.typeName, package: package)
      // The Go-tool (protocompile unlinked) does not resolve the `type` enum for
      // message/enum fields (type-linking is required). Clear it so both sides compare equally.
      f.clearType()
    }
    if !f.extendee.isEmpty {
      // Strip leading dot first.
      var extendee = f.extendee.hasPrefix(".") ? String(f.extendee.dropFirst()) : f.extendee
      // The Go-tool (unlinked) does not resolve simple extendee names to fully-qualified form.
      // SwiftProtoParser prepends the package name for simple names (matching protoc), so we
      // strip the package prefix here to make both sides comparable.
      if !package.isEmpty, extendee.hasPrefix(package + ".") {
        extendee = String(extendee.dropFirst(package.count + 1))
      }
      f.extendee = extendee
    }
    if f.hasOptions {
      f.options.uninterpretedOption = f.options.uninterpretedOption.map { normaliseAggregateValue($0) }
    }
    return f
  }

  private func normaliseSvcForGoTool(
    _ svc: Google_Protobuf_ServiceDescriptorProto,
    package: String
  ) -> Google_Protobuf_ServiceDescriptorProto {
    var s = svc
    if s.hasOptions {
      s.options.uninterpretedOption = s.options.uninterpretedOption.map { normaliseAggregateValue($0) }
    }
    s.method = s.method.map { m -> Google_Protobuf_MethodDescriptorProto in
      var m2 = m
      m2.inputType = normaliseTypeName(m2.inputType, package: package)
      m2.outputType = normaliseTypeName(m2.outputType, package: package)
      if m2.hasOptions {
        m2.options.uninterpretedOption = m2.options.uninterpretedOption.map { normaliseAggregateValue($0) }
      }
      return m2
    }
    return s
  }

  private func normaliseMessage(_ proto: Google_Protobuf_DescriptorProto) -> Google_Protobuf_DescriptorProto {
    var p = proto
    p.nestedType = p.nestedType.map { normaliseMessage($0) }
    // protoc intentionally strips ExtensionRangeOptions (declaration / verification)
    // from the serialised binary descriptor — they are compile-time validation metadata
    // only.  Clear them from both sides so the comparison is accurate.
    p.extensionRange = p.extensionRange.map { range in
      var r = range
      r.clearOptions()
      return r
    }
    return p
  }

  private func normaliseAggregateValue(
    _ u: Google_Protobuf_UninterpretedOption
  ) -> Google_Protobuf_UninterpretedOption {
    guard u.hasAggregateValue else { return u }
    var copy = u
    // Normalize whitespace: collapse multiple spaces, remove spaces around ':' and ','
    let raw = copy.aggregateValue
    let normalized =
      raw
      .components(separatedBy: .whitespaces)
      .filter { !$0.isEmpty }
      .joined(separator: " ")
    copy.aggregateValue = normalized
    return copy
  }

  // MARK: - Comparison

  private func assertBytesEqual(
    _ actual: Google_Protobuf_FileDescriptorProto,
    _ expected: Google_Protobuf_FileDescriptorProto,
    label: String,
    file: StaticString,
    line: UInt
  ) {
    do {
      let actualBytes: [UInt8] = try actual.serializedBytes()
      let expectedBytes: [UInt8] = try expected.serializedBytes()
      if actualBytes == expectedBytes { return }

      // Bytes differ: emit JSON diff for diagnostics
      let actualJSON = (try? actual.jsonString()) ?? "<json failed>"
      let expectedJSON = (try? expected.jsonString()) ?? "<json failed>"
      XCTFail(
        "Descriptor bytes mismatch for \(label).\n"
          + "--- expected ---\n\(expectedJSON)\n"
          + "--- actual ---\n\(actualJSON)",
        file: file,
        line: line
      )
    }
    catch {
      XCTFail("Serialization error for \(label): \(error)", file: file, line: line)
    }
  }

  // MARK: - Path helpers

  private func testResourcePath(for relativePath: String) -> String {
    let thisFile = URL(fileURLWithPath: #file)
    let projectRoot =
      thisFile
      .deletingLastPathComponent()  // ProductTests
      .deletingLastPathComponent()  // SwiftProtoParserTests
      .deletingLastPathComponent()  // Tests
      .deletingLastPathComponent()  // project root
    return projectRoot.appendingPathComponent("Tests/TestResources/\(relativePath)").path
  }

  // MARK: - Errors

  enum IntegrationTestError: Error {
    case parseFailed(String, String)
    case protoNotFound(String)
  }
}
