syntax = "proto3";

package test.subfield;

import "google/protobuf/descriptor.proto";

message Constraints {
  int32 gt = 1;
  int32 lt = 2;
  string pattern = 3;
}

message StringConstraints {
  uint64 max_len = 1;
  string pattern = 2;
}

message FieldConstraints {
  int32 int32_gt = 1;
  StringConstraints string = 2;
  Constraints nested = 3;
}

extend google.protobuf.FieldOptions {
  FieldConstraints validate = 51001;
}

message SubfieldMessage {
  int32 age = 1 [(validate).int32_gt = 0];
  string name = 2 [(validate).string.max_len = 255];
  string code = 3 [(validate).string.pattern = "^[A-Z]+$"];
  int32 score = 4 [(validate).nested.gt = 0];
  int32 level = 5 [(validate).nested.lt = 100];
}
