name: Swift Test

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.9'

      - name: Build and test with coverage
        run: swift test --enable-code-coverage --parallel
