name: Swift Test

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9.2-release
          platform: ubuntu22.04
          arch: aarch64

      - name: Build and test with coverage
        run: swift test --enable-code-coverage --parallel
