name: Swift Test

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9'

      - name: Build and test with coverage
        run: swift test --enable-code-coverage --parallel
